controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
  - name: fake_gripper_controller
    joints:
      - kinova_arm_joint_finger_1
      - kinova_arm_joint_finger_2
      - kinova_arm_joint_finger_3
initial:  # Define initial robot poses.
  - group: manipulator
    pose: stow
